concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "workflow"
  url = "http://gitlab.local:8081"
  id = 2
  token = "glrt-w6MK7xXyZJzMYA7FkyP71G86MQpwOjMKdDozCnU6MQ8.01.170f6cdxj"
  token_obtained_at = 2025-10-22T10:45:59Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    extra_hosts = ["harbor.local:192.168.88.15"]
    network_mode = "network-git"
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "Runner déploiement Docker hôte"
  url = "http://gitlab.local:8081"
  id = 3
  token = "glrt-VN0O9bMtV-bT4gUv3EYdwG86MQpwOjMKdDozCnU6MQ8.01.171xpksgx"
  token_obtained_at = 2025-10-25T04:06:32Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  tags = ["workflow-deploy"]
  run_untagged = false
  locked = false
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:24.0.5"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    extra_hosts = ["harbor.local:192.168.88.15", "gitlab.local:192.168.88.15"]
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0
    network_mtu = 0
